### ISSUE TITLE
cant set my own config

### ISSUE THREAD

**Issue by cfedersp** [l0rdn1kk0n/wicket-requirejs#8]
Given:
Setting my own IRequireJsSettings requires instantiating a ResourceReference representing the require.js javascript lib.
ResourceReferences cannot be created until RequireJs.install has been called.

Observed:
calling RequireJs.install(this, new MyRequireJsSettings()) results in the following error:
java.lang.IllegalStateException: you have to call WicketWebjars.install() before you can use an IWebjarsResourceReference or any other component.

**Comment by cfedersp** [comment]
Nevermind, I had a WebjarsJavaScriptResourceReference set as a static var, which I believe caused my issue.

**Comment by cfedersp** [comment]
This is legit. 
I cleaned up my code, this works:
`RequireJs.install(this);`
but the following breaks at deployment time:
`RequireJs.install(this, new RequireJsSettings());`

My ultimate goal was to use JQuery 2, which I am able to do anyway:
`RequireJs.install(this); 
getJavaScriptLibrarySettings().setJQueryReference(new WebjarsJavaScriptResourceReference("jquery/2.1.3/jquery.2.1.3.js"));`

**Comment by martin-g** [comment]
Could you please paste the exception stack trace?

**Comment by cfedersp** [comment]
The last line, starting with Caused by: java.lang.IllegalStateException provides a clue.


14:23:13,598 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/wellnessconnected]] (MSC service thread 1-14) Exception starting filter wicketPortalManager: java.lang.ExceptionInInitializerError
	at de.agilecoders.wicket.webjars.util.WebjarsVersion.useRecent(WebjarsVersion.java:46) [wicket-webjars-0.4.5.jar:]
	at de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference.<init>(WebjarsJavaScriptResourceReference.java:27) [wicket-webjars-0.4.5.jar:]
	at de.agilecoders.wicket.requirejs.RequireJsSettings.<init>(RequireJsSettings.java:29) [wicket-requirejs-0.1.2.jar:]
	at com.and.projectdouble.cloud.wicket.WcPortal.init(WcPortal.java:50) [wellnessconnected-lib-1.1.6.jar:]
	at org.apache.wicket.Application.initApplication(Application.java:823) [wicket-core-6.19.0.jar:6.19.0]
	at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:424) [wicket-core-6.19.0.jar:6.19.0]
	at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:351) [wicket-core-6.19.0.jar:6.19.0]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:447) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:3269) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3865) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_45]
	at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_45]
Caused by: java.lang.IllegalStateException: you have to call WicketWebjars.install() before you can use an IWebjarsResourceReference or any other component.
	at de.agilecoders.wicket.webjars.WicketWebjars.settings(WicketWebjars.java:133) [wicket-webjars-0.4.5.jar:]
	at de.agilecoders.wicket.webjars.util.WebjarsVersion$Holder.<clinit>(WebjarsVersion.java:29) [wicket-webjars-0.4.5.jar:]

**Comment by cfedersp** [comment]
This fork has a working solution candidate:
https://github.com/cfedersp/wicket-requirejs

In this fix, rather than creating a RequireJsSettings outright, we pass an instance of a factory that can create a RequireJsSettings once other dependencies have been met.
modified:   RequireJs.java
new: IRequireJsSettingsFactory.java
new: DefaultRequireJsSettingsFactory.java

hope this helps.

**Comment by martin-g** [comment]
The error says that `WicketWebjars` should be installed before `RequireJs`.
If you don't use WebJars then there shouldn't be a problem with RequireJs setup,with or without providing RequireJsSettings explicitly.

**Comment by cfedersp** [comment]
Or maybe I could start herding sheep in Kamchatka. Then I could print out all this code to use as kindling to stay warm on special occasions.

**Comment by martin-g** [comment]
I'm not following you.
Does the problem disappear if you `WicketWebjars.install(this)` before installing RequireJs?

**Comment by cfedersp** [comment]
Yes, thank you it does. 

I thought you were instructing me to write a new IRequireJsSettings implementation that did not use  webjars.

**Comment by martin-g** [comment]
Sorry. English is not my native language and sometimes such confusions happen.
I'm glad everything is OK now. I'll update the README.
